language: c
compiler: gcc
arch:
  amd64
  arm64

script: make describe tests rosettacode

addons:
  apt:
    packages:
        - gcc-multilib
        - linux-libc-dev:i386

sudo: false
git:
  depth: 1
branches:
  only:
    - master
